version: 0.0
os: linux
files:
  - source: ../bundle.tar
    destination: /var/lib/tomcat/webapps
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/restart_server.sh
      timeout: 300
      runas: root