version: 0.0
os: linux
files:
  - source: /home/ec2-user/PZDemoApp.war
    destination: /var/lib/tomcat/webapps
hooks:
  BeforeInstall:
    - location: /before_install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: /restart_server.sh
      timeout: 300
      runas: root